name: Update MLB Playoff Calendar

on:
  schedule:
    # Run every day at 6 AM ET (10 AM UTC)
    - cron: '0 10 * * *'
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 icalendar pytz
    
    - name: Generate calendar
      run: |
        python generate_calendar.py
    
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add mlb_playoffs.ics
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update MLB playoff calendar - $(date)" && git push)
